# Inherit Pure preset
"$schema" = 'https://starship.rs/config-schema.json'
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

# Get editor completions based on the config schema
command_timeout = 2000

# Disable the blank line at the start of the prompt
add_newline = true

# Directory config
[directory]
style = "blue"
truncate_to_repo = true

# A continuation prompt that displays two filled in arrows
continuation_prompt = "▶▶"

# Username config
[username]
style_user = "white"
style_root = "red"
format = "[$user]($style) "
disabled = false
show_always = false

[hostname]
ssh_only = true
format = "@ [$hostname](bold red) "
disabled = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[cmd_duration]
format = " [$duration]($style)"
style = "yellow"

[python]
format = ' [$virtualenv]($style) '
style = "bright-black"
